### ISSUE TITLE
full width layout problem

### ISSUE THREAD

**Issue by endcoreAK** [affiliatetheme/affiliatetheme#2]
### Discussed in https://github.com/affiliatetheme/affiliatetheme/discussions/1

<div type='discussions-op-text'>

<sup>Originally posted by **Chekki** January 10, 2023</sup>
Hi,

after updating to 2.0 the header layout is boxed instead of full width: 

https://fernstudium-in-deutschland.de/

I would like to have a full width header. The setting show full width:

![Bildschirm­foto 2023-01-10 um 10 46 56](https://user-images.githubusercontent.com/23417760/211524507-0d13107a-9471-431a-930e-6a3afedb4616.jpg)
![Bildschirm­foto 2023-01-10 um 10 47 01](https://user-images.githubusercontent.com/23417760/211524515-39738c21-77f5-4e43-9b17-bece495a3b58.jpg)

Before the update:

![Bildschirm­foto 2023-01-10 um 11 20 02](https://user-images.githubusercontent.com/23417760/211524989-7ca4189a-95cb-4fca-9c2f-6fcbf04cc5f1.jpg)

After update:

![Bildschirm­foto 2023-01-10 um 10 47 24](https://user-images.githubusercontent.com/23417760/211525056-f89ce6d8-a1b8-491a-b15e-da08c7ad1537.jpg)

What can I do to get full width back?

Best regards</div>

**Comment by endcoreAK** [comment]
You can use this code as a quickfix, as long as we need to review / publish the fix.

```
#wrapper,
.wrapped {
    width: auto;
}
```

**Comment by Chekki** [comment]
Thanks it works!

**Comment by Tobsen218** [comment]
I have the same problem. Wordpress has already been freshly set up 3 times. The Boxed and Full Width settings do not work.

**Comment by Tobsen218** [comment]
I just see that the answer was a year ago. Will anything else be fixed here? I just purchased ACF for this theme. I hope it's not full of errors like this.

**Comment by endcoreCL** [comment]
Fixed in next release
