### ISSUE TITLE
acf_get_value  problem 

### ISSUE THREAD

**Issue by Mag91** [affiliatetheme/affiliatetheme#23]
i get the following errors: 

Notice: Die Funktion acf_get_value wurde fehlerhaft aufgerufen. Advanced Custom Fields PRO – Es wurde mindestens ein Versuch festgestellt, ACF-Feldwerte abzurufen, bevor ACF initialisiert wurde. Dies wird nicht unterstützt und kann zu fehlerhaften oder fehlenden Daten führen. [Lerne, wie du das beheben kannst (engl.)](https://www.advancedcustomfields.com/resources/acf-field-functions/?utm_source=ACF+PRO&utm_medium=insideplugin&utm_campaign=docs&utm_content=early_init_warning). Weitere Informationen: [Debugging in WordPress (engl.)](https://wordpress.org/documentation/article/debugging-in-wordpress/). (Diese Meldung wurde in Version 5.11.1 hinzugefügt.) in /www/htdocs/w015334f/xxx.xxx/wp-includes/functions.php on line 5905

Notice: Die Funktion acf_get_value wurde fehlerhaft aufgerufen. Advanced Custom Fields PRO – Es wurde mindestens ein Versuch festgestellt, ACF-Feldwerte abzurufen, bevor ACF initialisiert wurde. Dies wird nicht unterstützt und kann zu fehlerhaften oder fehlenden Daten führen. [Lerne, wie du das beheben kannst (engl.)](https://www.advancedcustomfields.com/resources/acf-field-functions/?utm_source=ACF+PRO&utm_medium=insideplugin&utm_campaign=docs&utm_content=early_init_warning). Weitere Informationen: [Debugging in WordPress (engl.)](https://wordpress.org/documentation/article/debugging-in-wordpress/). (Diese Meldung wurde in Version 5.11.1 hinzugefügt.) in /www/htdocs/w015334f/xxx.xxx/wp-includes/functions.php on line 5905

Notice: Die Funktion acf_get_value wurde fehlerhaft aufgerufen. Advanced Custom Fields PRO – Es wurde mindestens ein Versuch festgestellt, ACF-Feldwerte abzurufen, bevor ACF initialisiert wurde. Dies wird nicht unterstützt und kann zu fehlerhaften oder fehlenden Daten führen. [Lerne, wie du das beheben kannst (engl.)](https://www.advancedcustomfields.com/resources/acf-field-functions/?utm_source=ACF+PRO&utm_medium=insideplugin&utm_campaign=docs&utm_content=early_init_warning). Weitere Informationen: [Debugging in WordPress (engl.)](https://wordpress.org/documentation/article/debugging-in-wordpress/). (Diese Meldung wurde in Version 5.11.1 hinzugefügt.) in /www/htdocs/w015334f/xxx.xxx/wp-includes/functions.php on line 5905

Warning: Undefined array key "WP_Widget_Recent_Comments" in /www/htdocs/w015334f/xxx.xxx/wp-content/themes/affiliatetheme/library/helper/filter.php on line 168

the acf support tells me to ask here. i have installed the website normally as i think i started a blank webpage so no update from the old affiliatetheme version what can i do?

**Comment by Mag91** [comment]
The startpage is not loading at all. only the errors. ( as i remember i turned the debug mode on) the other pages are loading but on the top are the same error messages. seems like there is something not working with the products or other field problems

**Comment by olaf-schmitz** [comment]
Did you install V2 of Affiliatetheme (download from GitHub) and have an ACF Pro paid license installed?

**Comment by Mag91** [comment]
yes i have done exact this. i don't know what i was doing wrong... i tryed the Affiliate Theme 2.0 and the Affiliate Theme CHild theme version 1.0 nd just made an update of the ACF Pro paid plugin and all other plugins. If i change the theme to Twenty Seventeen as the ACF Pro support suggested the errors disappear

**Comment by Mag91** [comment]
do you have an ideas what todo?

**Comment by Roman-Wo** [comment]
Bei mir ist ein ähnliches Problem aufgetreten, das dieselben Fehlerhinweise zeigt. Gibt es inzwischen eine Lösung von den betreffenden Parteien - ACF und AT?

**Comment by endcoreCL** [comment]
https://github.com/affiliatetheme/affiliatetheme/releases/tag/v2.1

Release 2.1 fixed this issue :)
