### ISSUE TITLE
PHP Warning

### ISSUE THREAD

**Issue by Chauffe** [affiliatetheme/affiliatetheme#24]
I get the following message in my server error logs: Got error 'PHP message: PHP Warning: Undefined array key 1 in /xxx/wp-content/themes/affiliatetheme/taxonomy.php on line 31

**Comment by endcoreCL** [comment]
https://github.com/affiliatetheme/affiliatetheme/releases/tag/v2.1

Release 2.1 fixed this issue :)

**Comment by Chauffe** [comment]
Thanks for the quick fix. After updating I got a critical error. Luckily I had made a backup and restored my site.
