### ISSUE TITLE
Can not activate ACF Pro

### ISSUE THREAD

**Issue by Benyef** [affiliatetheme/affiliatetheme#3]
Hello.
I try to acitvate my Licence.
But i dont have the "Update" Page.
I installed the PRO Version.

I also dont know how i can change it in the wp-config.php

What can i do?
![Screenshot 2023-01-14 102934](https://user-images.githubusercontent.com/122670820/212466035-9df3dd97-96e0-4eb1-b570-e8fbf3c2262f.png)

**Comment by StrongLucky** [comment]
Seems the old (not pro) version is activated. Can you check the plugin list?

**Comment by Benyef** [comment]
HI.
I used the newest version.

![Screenshot 2023-01-14 135441](https://user-images.githubusercontent.com/122670820/212473158-acc8bf8c-5c56-4954-ac5b-f52a374b50de.png)

**Comment by StrongLucky** [comment]
Ok looks good. If you are still using affiliatetheme 1.x it might have a conflict with the integrated ACF verstion in the theme.

So just update the affiliatetheme and it will work. After the upgrade you might see the tab where you can enter your key.

For your interest: The affiliatetheme will also work without the key. You can not get automatic updates for ACF without a license.

**Comment by Benyef** [comment]
i cant install the new theme. As you can see on my screenshots.

Also i cant install version 1.8.4.

?

![Screenshot 2023-01-14 144812](https://user-images.githubusercontent.com/122670820/212475268-8847ba5e-e215-4c3e-abd5-e75a50536e2b.png)
![Screenshot 2023-01-14 144843](https://user-images.githubusercontent.com/122670820/212475269-02339f4b-25d7-40cb-8fee-f0a755f16861.png)
![Screenshot 2023-01-14 144936](https://user-images.githubusercontent.com/122670820/212475271-d74087ca-4673-4c6d-a572-a9eb82cce5a1.png)

**Comment by StrongLucky** [comment]
You have to install the theme under themes. Not under plugins.

Have a closer look at the pictures in the german guide: [https://affiliatetheme.io/upgrade-auf-2-0/](https://affiliatetheme.io/upgrade-auf-2-0/)

**Comment by Benyef** [comment]
Thx. It does work so.
