### ISSUE TITLE
characteristicsfields of products missing on mobile view

### ISSUE THREAD

**Issue by Benyef** [affiliatetheme/affiliatetheme#4]
On my Desktop Browser i can see the characteristicsfields of my products.

When i open the same page on my phone, it will show the product but without characteristicsfields.

How can i make this fields also visible for mobilephones?

![Screenshot 2023-01-14 154802](https://user-images.githubusercontent.com/122670820/212477879-8c42d2f7-56b7-4ca5-b69a-b3d7c9fc1546.png)
![Screenshot_2023-01-14-15-48-44-804_com opera browser](https://user-images.githubusercontent.com/122670820/212477906-b1050e4d-2ee9-435d-93f8-e6c4ae7f52ba.jpg)

**Comment by endcoreAK** [comment]
The table with the product data is hidden in the theme, so that it is clearer and more compact. With the CSS code you can make it visible:

`.product-list .caption .col-md-pull-3.hidden-xs { display: block !important; margin-top: 1rem; }`
