### ISSUE TITLE
Ebay Schnittstelle Cronjob Umstellung 

### ISSUE THREAD

**Issue by heinz24** [affiliatetheme/affiliatetheme#7]
Damit lässt sich doch auf 6 Stunden umstellen:
wp_schedule_event( time(), '6_hours', 'affiliatetheme_ebay_api_update', $args = array( 'hash' => EBAY_CRON_HASH ) );
Zeigt aber keine Wirkung mehr, es bleibt nach wie vor auf 1 Stunden.
Über WP Control sehe ich zwar das 6 Stunden eingestellt sind, darüber steht aber W hourly.
Im API log sehe ich noch immer eine stündliche Abfrage der Produkte.
Der WP Cronjob hat wieder Einfluss, vermutlich durch Update?
Wo kann ich das ausschalten?

**Comment by StrongLucky** [comment]
Hallo heinz24,

du musst eine kleine Änderungen an dem Code vornehmen:

`wp_schedule_event( time(), '6_hours', 'affiliatetheme_ebay_api_update', $args = array( EBAY_CRON_HASH ) );`

array( 'hash' => EBAY_CRON_HASH ) wird zu  array( EBAY_CRON_HASH )

Beste Grüße
Lucas

**Comment by heinz24** [comment]
Hallo Lucas,
So schaut das jetzt komplett aus, ist das so richtig? 
Daher insgesamt 3 Zeilen mit der Änderung.
Vielen Dank für Deine Info! 
Viele Grüße
Heinz

if ( get_option( 'ebay_app_id' ) != "" ) {
        if ( ! wp_next_scheduled( 'affiliatetheme_ebay_api_update', $args = array( EBAY_CRON_HASH ) ) ) {
               wp_schedule_event( time(), '6_hours', 'affiliatetheme_ebay_api_update', $args = array( EBAY_CRON_HASH ) ); 
        }
} else {
        //wp_clear_scheduled_hook('affiliatetheme_ebay_api_update', $args = array( EBAY_CRON_HASH));
}
add_action( 'wp_ajax_ebay_api_update', 'at_ebay_update' );
add_action( 'wp_ajax_nopriv_ebay_api_update', 'at_ebay_update' );
add_action( 'wp_ajax_at_ebay_update', 'at_ebay_update' );
add_action( 'wp_ajax_nopriv_at_ebay_update', 'at_ebay_update' );
add_action( 'affiliatetheme_ebay_api_update', 'at_ebay_update' );
function at_ebay_update( $args = array() )
{
        global $wpdb;

        $hash       = EBAY_CRON_HASH;
        $check_hash = ( $args ? $args : ( isset( $_GET['hash'] ) ? $_GET['hash'] : '' ) );

        if ( $check_hash != $hash ) {
                wp_clear_scheduled_hook( 'affiliatetheme_ebay_api_update', $args = array( 'hash' => $check_hash ) );
                die( 'Security check failed.' );
        }

**Comment by StrongLucky** [comment]
Sieht gut aus.

Wenn du den Code im Plugin selbst änderst, muss dir bewusst sein, dass die Änderungen mit dem nächsten Update weg sind.

**Comment by heinz24** [comment]
OK ist klar, vielen Dank.

**Comment by heinz24** [comment]
Hallo Lucas,
Das API Log zeigt keine Veränderung, es läuft noch immer der 1 Stunden cron.
Habe auch das Plugin nach der Änderung neu gestartet, verwende noch  Version 1.4.2.2 da im April im Vorjahr einige Anpassungen nach meinen Wunsch von Christian eingebaut wurden. Bei der neuen Version fallen die alle raus, daher diese.
Das Problem ist, das Ebay zu viele API Abfragen bekommt und ich zeitweilig keine Produkte mehr hochgeladen kann.

**Comment by StrongLucky** [comment]
Hast du einen CronManager in WP installiert? Eventuell laufen die Cronjobs jetzt auch doppelt.
Dann könntest du über einen Manager einfach den falschen löschen bzw. stoppen.

Dafür kannst z. B. "WP Crontrol" nehmen. Findest du direkt über Plugins in WP.

**Comment by heinz24** [comment]
Habe zwei Einträge gefunden:
Dieser war auf 1 Stunde, habe ich jetzt über WP Control auf 6 Stunden eingestellt:
affiliatetheme_ebay_api_updateBearbeiten  [     "4a6a30aa6f580661d87d1fa5650ac7f5" ] | 2023-02-07 15:39:418 Minuten 26 Sekunden | at_ebay_update() | every 6 Hours
Es gibt noch einen zweiten Eintrag:
check_plugin_updates-affiliatetheme-ebayBearbeiten \|  | 2023-02-07 20:34:545 Stunden 3 Minuten | PluginUpdateChecker_2_2->maybeCheckForUpdates() | Zweimal täglich
Das dürfte aber nur mit den Plugin zu tun haben.
